version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    image: postman-course_web_1
    build: .
    command: python project/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
